### ISSUE TITLE
BR

### ISSUE THREAD

**Issue by xingzjx** [Kelin-Hong/MVVMLight#5]
你好，BR.viewModel中的BR类找不到怎么回事

**Comment by Kelin-Hong** [comment]
File > Invalidate Caches/Restart

**Comment by xingzjx** [comment]
自己参考写的一个demo，BR文件还是无法生成？

**Comment by Kelin-Hong** [comment]
项目能跑起来吗?  IDE 有时候BR会显示找不到，但是不影响编译，有什么问题 贴个log我看下。

**Comment by xingzjx** [comment]
itemView.set(BR.viewModel,R.layout.item_news_list);   BR是红色，找不到。运行没有问题，但是看不到RecycleView的每个item

**Comment by xingzjx** [comment]
BR文件没有，不影响运行，就是无法展示数据效果

**Comment by Kelin-Hong** [comment]
偶尔也会遇到没有BR文件，BR处代码飘红，但是只是影响编码，并不影响展示数据的

**Comment by xingzjx** [comment]
有没办法忽略BR文件飘红，

**Comment by Kelin-Hong** [comment]
印象中好像有遇到过，不过后来自己好了，目前还不知道有什么办法。只能File > Invalidate Caches/Restart 试试
