### ISSUE TITLE
图片加载问题

### ISSUE THREAD

**Issue by xingzjx** [Kelin-Hong/MVVMLight#6]
你好，在Application里面初始化了Fresco，但是ImageView无法显示图片

**Comment by xingzjx** [comment]
adapter（还有某些属性）获取不到

**Comment by Kelin-Hong** [comment]
我这边是正常的，你再看看，Fresco 是可选的，你可以不用它，用其他图片库也行，adapter（还有某些属性）获取不到 是什么意思呢？

**Comment by xingzjx** [comment]
已经解决了，谢谢

**Comment by git-cncoder** [comment]
您好。可以稍微说一下思路， 如何使用其他库加载图片吗。谢谢.
